### ISSUE TITLE
android crashes after update flutter 

### ISSUE THREAD

**Issue by AhkamKhalaaf** [icapps/flutter-background-location-tracker#57] opened 2023-07-13 09:51 UTC
when i run android , it gives this error 
 D/FlutterLocationService( 5294): Creating service.
D/FlutterLocationService( 5294): Binding to location service.
Lost connection to device.
, 
the output of flutter doctor -v 
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F82 darwin-arm64, locale en-EG)
    • Flutter version 3.10.6 on channel stable at /Users/ahkamahkam/Documents/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (11 hours ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/ahkamahkam/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /Users/ahkamahkam/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.76.2)
    • VS Code at /Users/ahkamahkam/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.64.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554                        • android-arm64 • Android 12 (API 31) (emulator)
    • iPhone 13 (mobile)          • 7CE6E17B-E2B1-482F-B711-3D518D07BA94 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)

[✓] Network resources
    • All expected network resources are available.

• No issues found!
my pubcpec.yaml 
dependencies:
  auto_size_text: ^3.0.0-nullsafety.0
  bot_toast: ^4.0.1
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  collection: ^1.15.0
  cookie_jar: ^4.0.5
  dio: ^5.2.1+1
  dio_cookie_manager: ^3.1.0
  easy_localization: ^3.0.0
  encrypt: ^5.0.0
  firebase_analytics: ^10.0.4
  flutter:
    sdk: flutter
  flutter_bug_logger: ^1.0.0
  flutter_cache_manager: ^3.3.0
  flutter_dotenv: ^5.0.2
  flutter_gen: ^5.1.0+1
  flutter_html: ^3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: ^1.0.2
  geocoding: ^2.0.0
  google_fonts: ^4.0.4
  images_picker: ^1.2.11
  in_app_review: ^2.0.2
  line_awesome_flutter: ^2.0.0
  location: ^5.0.0
  package_info: ^2.0.2
  percent_indicator: ^4.2.2
  app_settings: ^5.0.0
  background_location_tracker: ^1.4.0
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.3
  infinite_scroll_pagination: ^3.1.0
  connectivity_plus: ^4.0.1
dev_dependencies:
  build_runner: ^2.3.2
  device_preview: ^1.1.0
  #To get unused files => flutter pub run dart_code_metrics:metrics check-unused-files lib
  dart_code_metrics: ^5.0.1
  flutter_gen_runner: ^5.0.3

  #To generate app icons => flutter pub run flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1

  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^2.1.2
any help about this problem @ikbendewilliam

**Comment by ikbendewilliam** [comment] 2023-07-14 07:44
Hi @AhkamKhalaaf I'll have a look at it, I will close this issue as you've already opened one before
duplicate of #56

**Closed by ikbendewilliam** 2023-07-14 07:44 UTC
