### ISSUE TITLE
Altitude

### ISSUE THREAD

**Issue by aospiridonov** [icapps/flutter-background-location-tracker#37] opened 2022-03-17 13:37 UTC
Please add altitude

**Comment by vanlooverenkoen** [comment] 2022-07-15 11:26
We do accept pull request, for us this is currently not a high prio. But we will review & merge a pull request if you make one.

**Comment by vanlooverenkoen** [comment] 2022-09-07 10:48
Duplicate of #21

**Closed by vanlooverenkoen** 2022-09-07 10:48 UTC
Labels: feature, accepting-pull-requests
