### ISSUE TITLE
infinite repeat   backgroundCallback when First time only install app for any device android 

### ISSUE THREAD

**Issue by AhkamKhalaaf** [icapps/flutter-background-location-tracker#62] opened 2023-09-10 18:50 UTC
infinite repeat backgroundCallback when First time only install app for any device android , 
but when run application second  time , it works normally 
, this my backgroundCallBack 
```dart
@pragma('vm:entry-point')
void backgroundCallback() {
  BackgroundLocationTrackerManager.handleBackgroundUpdated(
      (BackgroundLocationUpdateData data) async {
    try {
      await providerContainer.read(currentLocationProvider).saveUserLocation(data: data);
    } catch (onError) {
      debugPrint('$onError');
    }
  });
}, 
my configuration 
  await BackgroundLocationTrackerManager.initialize(
    backgroundCallback,
    config: const BackgroundLocationTrackerConfig(
      androidConfig: AndroidConfig(
        distanceFilterMeters: 100,
        trackingInterval: Duration(minutes: 5),
        enableCancelTrackingAction: false,
      ),
      iOSConfig: IOSConfig(
        activityType: ActivityType.FITNESS,
        distanceFilterMeters: 100,
        restartAfterKill: true,
      ),
    ),
  );
```
@ikbendewilliam any help about this issue

**Comment by ikbendewilliam** [comment] 2023-09-11 06:43
@AhkamKhalaaf Do you do `WidgetsFlutterBinding.ensureInitialized();` before the `await BackgroundLocationTrackerManager.initialize`?

**Comment by ikbendewilliam** [comment] 2023-09-11 06:45
@AhkamKhalaaf I see you've already opened an issue for this, we'll discuss it further there to prevent confusion.

**Comment by ikbendewilliam** [comment] 2023-09-11 06:45
duplicate of 54

**Closed by ikbendewilliam** 2023-09-11 06:45 UTC
